pip install Cython
pip install Jinja2
pip install MarkupSafe
pip install Pillow
pip install Pygments
pip install appnope
pip install argparse
pip install backports-abc
pip install backports.ssl-match-hostname
pip install certifi
pip install cycler
pip install decorator
pip install future
pip install gnureadline
pip install h5py
pip install ipykernel
pip install ipython
pip install ipython-genutils
pip install ipywidgets
pip install jsonschema
pip install matplotlib
pip install mistune
pip install nbconvert
pip install nbformat
pip install nltk
pip install numpy
pip install path.py
pip install pexpect
pip install pickleshare
pip install ptyprocess
pip install pyparsing
pip install python-dateutil
pip install pytz
pip install pyzmq
pip install qtconsole
pip install scipy
pip install simplegeneric
pip install singledispatch
pip install six
pip install terminado
pip install tornado
pip install traitlets
conda install jupyter
